# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  artifact-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: |
          go get .
      - name: Build darwin
        if: matrix.os == 'macos-latest'
        run: |
          go build -o build-macos-latest-amd64
      - name: Build linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          go build -o build-ubuntu-latest-amd64
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: build-${{ matrix.os }}-amd64
          path: build-${{ matrix.os }}-amd64
